/**
 * Supabase backend.
 *
 * Money columns are bigint minor units on both sides, so rows map across
 * almost directly; the few conversions are numeric columns that Supabase
 * returns as strings.
 */

import type { SupabaseClient } from '@supabase/supabase-js'
import type { PublicQuoteView, Repository, Snapshot } from '../repository'
import type {
  BusinessProfile, Customer, FollowUp, Job, NoteScan, PriceBookItem, Quote, QuoteItem,
} from '@/types/domain'
import { calculateTotals } from '@/lib/money'
import { getSupabase } from './client'

function unwrap<T>(result: { data: T | null; error: { message: string } | null }): T {
  if (result.error) throw new Error(result.error.message)
  return result.data as T
}

const num = (value: unknown, fallback = 0): number => {
  const parsed = typeof value === 'string' ? Number.parseFloat(value) : (value as number)
  return Number.isFinite(parsed) ? parsed : fallback
}

const nullableNum = (value: unknown): number | null =>
  value === null || value === undefined ? null : num(value)

/* Row mappers — the database returns numerics as strings. */
const toQuote = (row: Record<string, unknown>): Quote =>
  ({ ...row, gst_rate: num(row.gst_rate), subtotal: num(row.subtotal), gst_amount: num(row.gst_amount), total: num(row.total) }) as Quote

const toQuoteItem = (row: Record<string, unknown>): QuoteItem =>
  ({ ...row, quantity: num(row.quantity, 1), cost: nullableNum(row.cost), markup: nullableNum(row.markup), selling_price: num(row.selling_price) }) as QuoteItem

const toPriceBookItem = (row: Record<string, unknown>): PriceBookItem =>
  ({ ...row, cost: nullableNum(row.cost), markup: nullableNum(row.markup), selling_price: num(row.selling_price) }) as PriceBookItem

const toBusiness = (row: Record<string, unknown>): BusinessProfile =>
  ({ ...row, gst_rate: num(row.gst_rate, 0.15) }) as BusinessProfile

export class SupabaseRepository implements Repository {
  readonly kind = 'supabase' as const
  private readonly db: SupabaseClient

  constructor(client: SupabaseClient = getSupabase()) {
    this.db = client
  }

  async loadSnapshot(): Promise<Snapshot> {
    const businessRow = unwrap(
      await this.db.from('business_profile').select('*').limit(1).maybeSingle(),
    )
    if (!businessRow) {
      throw new Error(
        'No business profile found. Run the migration and seed in supabase/ before using the Supabase backend.',
      )
    }
    const business = toBusiness(businessRow)

    const [customers, quotes, quoteItems, priceBook, followUps, jobs, noteScans] = await Promise.all([
      this.db.from('customers').select('*').eq('business_id', business.id).order('name'),
      this.db.from('quotes').select('*').eq('business_id', business.id).order('created_at', { ascending: false }),
      this.db.from('quote_items').select('*').order('sort_order'),
      this.db.from('price_book_items').select('*').eq('business_id', business.id).order('name'),
      this.db.from('follow_ups').select('*').order('scheduled_for'),
      this.db.from('jobs').select('*').eq('business_id', business.id).order('created_at', { ascending: false }),
      this.db.from('note_scans').select('*').order('created_at', { ascending: false }),
    ])

    return {
      business,
      customers: unwrap(customers) as Customer[],
      quotes: (unwrap(quotes) as Record<string, unknown>[]).map(toQuote),
      quoteItems: (unwrap(quoteItems) as Record<string, unknown>[]).map(toQuoteItem),
      priceBook: (unwrap(priceBook) as Record<string, unknown>[]).map(toPriceBookItem),
      followUps: unwrap(followUps) as FollowUp[],
      jobs: unwrap(jobs) as Job[],
      noteScans: unwrap(noteScans) as NoteScan[],
    }
  }

  async saveBusiness(business: BusinessProfile): Promise<BusinessProfile> {
    return toBusiness(unwrap(await this.db.from('business_profile').upsert(business).select().single()))
  }

  async upsertCustomer(customer: Customer): Promise<Customer> {
    return unwrap(await this.db.from('customers').upsert(customer).select().single()) as Customer
  }

  async deleteCustomer(id: string): Promise<void> {
    unwrap(await this.db.from('customers').delete().eq('id', id).select())
  }

  async upsertQuote(quote: Quote): Promise<Quote> {
    // `public_token` is generated by the database and never round-tripped.
    return toQuote(unwrap(await this.db.from('quotes').upsert(quote).select().single()))
  }

  async deleteQuote(id: string): Promise<void> {
    unwrap(await this.db.from('quotes').delete().eq('id', id).select())
  }

  async replaceQuoteItems(quoteId: string, items: QuoteItem[]): Promise<QuoteItem[]> {
    const quoteRow = unwrap(
      await this.db.from('quotes').select('gst_inclusive,gst_rate').eq('id', quoteId).single(),
    ) as Record<string, unknown>
    const totals = calculateTotals(items, Boolean(quoteRow.gst_inclusive), num(quoteRow.gst_rate, 0.15))
    const payload = items.map(({ id, description, quantity, unit, cost, markup, selling_price, type, notes, sort_order }) => ({
      id, description, quantity, unit, cost, markup, selling_price, type, notes, sort_order,
    }))

    const result = unwrap(await this.db.rpc('replace_quote_items', {
      p_quote_id: quoteId,
      p_items: payload,
      p_subtotal: totals.subtotal,
      p_gst_amount: totals.gst_amount,
      p_total: totals.total,
    })) as Record<string, unknown>[]

    return result.map(toQuoteItem)
  }

  async upsertPriceBookItem(item: PriceBookItem): Promise<PriceBookItem> {
    return toPriceBookItem(unwrap(await this.db.from('price_book_items').upsert(item).select().single()))
  }

  async deletePriceBookItem(id: string): Promise<void> {
    unwrap(await this.db.from('price_book_items').delete().eq('id', id).select())
  }

  async upsertFollowUp(followUp: FollowUp): Promise<FollowUp> {
    return unwrap(await this.db.from('follow_ups').upsert(followUp).select().single()) as FollowUp
  }

  async replaceFollowUps(quoteId: string, followUps: FollowUp[]): Promise<FollowUp[]> {
    unwrap(await this.db.from('follow_ups').delete().eq('quote_id', quoteId).select())
    if (followUps.length === 0) return []
    return unwrap(await this.db.from('follow_ups').insert(followUps).select()) as FollowUp[]
  }

  async upsertJob(job: Job): Promise<Job> {
    return unwrap(await this.db.from('jobs').upsert(job).select().single()) as Job
  }

  async upsertNoteScan(scan: NoteScan): Promise<NoteScan> {
    return unwrap(await this.db.from('note_scans').upsert(scan).select().single()) as NoteScan
  }

  async storeNoteImage(scanId: string, file: File): Promise<string> {
    if (!file.type.startsWith('image/')) throw new Error('Only image files can be stored.')
    if (file.size > 10 * 1024 * 1024) throw new Error('That photo is larger than the 10 MB limit.')

    const business = unwrap(
      await this.db.from('business_profile').select('id').limit(1).maybeSingle(),
    ) as { id: string } | null
    if (!business?.id) throw new Error('No business profile found.')

    const extension = file.type === 'image/png' ? 'png' : file.type === 'image/webp' ? 'webp' : 'jpg'
    const path = `${business.id}/${scanId}/${crypto.randomUUID()}.${extension}`
    const uploaded = await this.db.storage.from('note-scans').upload(path, file, {
      cacheControl: '3600',
      contentType: file.type,
      upsert: false,
    })
    if (uploaded.error) throw new Error(uploaded.error.message)
    return path
  }

  async loadPublicQuote(token: string): Promise<PublicQuoteView | null> {
    // Read through a security-definer function so an anonymous visitor can see
    // exactly one quote by token and cannot enumerate the table.
    const payload = unwrap(await this.db.rpc('public_quote', { token })) as {
      quote: Record<string, unknown>
      items: Record<string, unknown>[]
      customer: Customer | null
      business: Record<string, unknown>
    } | null
    if (!payload?.quote) return null

    return {
      quote: toQuote(payload.quote),
      items: payload.items.map(toQuoteItem),
      customer: payload.customer,
      business: toBusiness(payload.business),
    }
  }

  async decidePublicQuote(token: string, decision: 'accepted' | 'declined'): Promise<void> {
    const result = unwrap(await this.db.rpc('decide_public_quote', { token, decision })) as
      | { ok: boolean; reason?: string }
      | null
    if (!result?.ok) {
      throw new Error(
        result?.reason === 'not_open'
          ? 'This quote is no longer awaiting a response.'
          : 'Could not record that decision.',
      )
    }
  }
}
